services:
  # ollama:
  #   container_name: ollama_cpu
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.ollama_cpu
  #   volumes:
  #     - ${USER_PATH}/${OLLAMA_PATH}/models:/root/.ollama
  #     - ${USER_PATH}/${OLLAMA_PATH}/home:/home/ollama
  #   ports:
  #     - "11434:11434"
  #     - "18789:18789"
  #   stdin_open: true
  #   tty: true
  #   networks:
  #     - agents
  ollama:
    container_name: ollama_amd
    build:
      context: .
      dockerfile: Dockerfile.ollama_amd
    devices:
      - /dev/kfd:/dev/kfd
      - /dev/dri:/dev/dri
    volumes:
      - ${USER_PATH}/${AGENT_PATH}/models:/root/.ollama
      - ${USER_PATH}/${AGENT_PATH}/ollama:/home/ollama
    ports:
      - "11434:11434"
      - "18789:18789"
    stdin_open: true
    tty: true
    networks:
      - agents
  # agent:
  #   container_name: agent
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.agent
  #   environment:
  #       # LA CLAVE: Aquí le dices al agente dónde está Ollama
  #       - OLLAMA_BASE_URL=http://ollama:11434
  #   volumes:
  #     - ${USER_PATH}/${AGENT_PATH}/agent:/home/agent
  #   ports:
  #     - "80:80"
  #     - "18790:18789"
  #   depends_on:
  #       - ollama
  #   stdin_open: true
  #   tty: true
  #   networks:
  #     - agents
  open-webui:
    container_name: open-webui
    image: ghcr.io/open-webui/open-webui:main
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ${USER_PATH}/${AGENT_PATH}/open-webui:/app/backend/data
    ports:
      - "3000:8080"
    restart: always
    networks:
      - agents
networks:
  agents:
    external: true
    name: agents
