services:
  ollama:
    container_name: ollama_custom
    build:
      context: .
      dockerfile: Dockerfile.ollama
    devices:
      - /dev/kfd:/dev/kfd
      - /dev/dri:/dev/dri
    volumes:
      - ${USER_PATH}/ollama/models:/root/.ollama
      - ${USER_PATH}/ollama/home:/home/ollama
    ports:
      - "11434:11434"
      - "18789:18789"
    stdin_open: true
    tty: true
    networks:
      - agents
  open-webui:
    container_name: open-webui
    image: ghcr.io/open-webui/open-webui:main
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ${USER_PATH}/open-webui:/app/backend/data
    ports:
      - "3000:8080"
    restart: always
    networks:
      - agents
networks:
  agents:
    external: true
    name: agents
